import './globals.css';
import {Noto_Sans_KR} from 'next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const notoSansKr = Noto_Sans_KR({
  subsets:['cyrillic'],
  weight: ['400', '700'],
  display: 'swap',

})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={notoSansKr.className}>
      <body>{children}</body>
    </html>
  )
}
